### ISSUE TITLE
chasis fan not working 

### ISSUE THREAD

**Issue by casagrandejonatan** [Luigisvc/Biqu-B1_Custom_Firmware#1]
Hi! Write your firmware on my biqu b1 skr 2 rev b. Fan chasis not working , only work hotend fans.

**Comment by casagrandejonatan** [comment]
2.0.9.4 not work , work fine 2.0.9.3

**Comment by Luigisvc** [comment]
hi vs 2.0.9.4 was compiled only for skr 1.4 turbo will not work with skr2. latest version for skr 2 is 2.0.9.3. 
is there vs 2.1.1.2 is out but i did not test yet

**Comment by casagrandejonatan** [comment]
Ok . Do you can upload config.h and config_adv.h for skr 2 marlin 2.0.9.3?
I can build custom firmware from latest marlin stable and share with you.

Happy new year.

My repo is github.com/jonatancasagrande

**Comment by Luigisvc** [comment]
sorry, i confused the versions, Actually the last version was 2.0.9.4 and is working in my b1 with skr2. you can download the sources from my github  [Luigisvc](https://github.com/Luigisvc) /
[Marlin_Sources](https://github.com/Luigisvc/Marlin_Sources)
I am on vacations now and cannot test firmwares on my printer.

**Comment by casagrandejonatan** [comment]
Ok , thanks sir. I download and create my custom firmware based in your
marlin source files.

**Comment by Luigisvc** [comment]
Please note I have compiled the new 2.1.2 and fans are working.
