### ISSUE TITLE
THIngiverse link for the Bl Touch support is broken

### ISSUE THREAD

**Issue by EricDimitri** [Luigisvc/Biqu-B1_Custom_Firmware#3]
Would you mind providing a working link, or any other way of knowing which is the support that has to be used?

Thank you!!!!

Great files by the way, you are helping a lot :)

**Comment by Luigisvc** [comment]
Hi, Sorry I didn't know the link was off, I found the same model in Printables, I am updating the readme file to reflect this link. Thanks for advise .

https://www.printables.com/model/79273-biqu-b1-bltouch-mount
